### ISSUE TITLE
SALOME's multi-desktop  user  interface

### ISSUE THREAD

**Issue by louislau86** [SalomePlatform/gui#2]
Does SALOME's GUI framework support displaying windows or views of different processes within a single main window framework？

**Comment by nitawa** [comment]
Hi Martin,
maybe someone in the core developer team can help here ?
Thanks

**Comment by martin-bernhard** [comment]
@louislau86 , can you please give some more details on how you would like to use SALOME or describe your scenario?

In the current state, SALOME may launch multiple instances for high-performant parallel calculations, even on different nodes, and finally all results will then be displayed in the main GUI instance.  
If you want to run a main GUI instance and then "remote control" it from another instance, I think this is not possible.

**Comment by louislau86** [comment]
> @louislau86 , can you please give some more details on how you would like to use SALOME or describe your scenario?
> 
> In the current state, SALOME may launch multiple instances for high-performant parallel calculations, even on different nodes, and finally all results will then be displayed in the main GUI instance. If you want to run a main GUI instance and then "remote control" it from another instance, I think this is not possible.
Thanks for your reply！My question is whether MainGUI can load and display the windows from other processes. For example, I have several other child processes that come with their own windows. I need to load and display these windows in a main program, which looks like there is only one process from the GUI

**Comment by louislau86** [comment]
> @louislau86 , can you please give some more details on how you would like to use SALOME or describe your scenario?
> 
> In the current state, SALOME may launch multiple instances for high-performant parallel calculations, even on different nodes, and finally all results will then be displayed in the main GUI instance. If you want to run a main GUI instance and then "remote control" it from another instance, I think this is not possible.

@martin-bernhard Thanks for your reply！My question is whether MainGUI can load and display the windows from other processes. For example, I have several other child processes that come with their own windows. I need to load and display these windows in a main program, which looks like there is only one process from the GUI

**Comment by martin-bernhard** [comment]
If these windows are modal dialogs for settings or alerts, you should be fine.
If you have written your own Salome module and want to have continuous access to your data/parameters/settings, then you probably want to integrate your GUI similar to what was done for the ObjectBrowser or the Inspection or Help panel.
Can you share some code or screenshots of what your processes are doing?

**Comment by louislau86** [comment]
Sorry，I am currently only investigating this possibility. I hope to create a system that consists of a main process with a GUI, as well as many other service processes with GUI. I will require that the GUI style of these service processes be consistent with that of the main process GUI. I think the GUI of these service processes can be directly embedded into my main process GUI, so that my entire system is modularized in a process manner, but integrated with the GUI of the main process. Although I know that every GUI program has its own UI message loop and achieving the desired effect is a difficult task, I still want to explore the possibilities. Because I have seen the architecture and features of SALOME, I would like to confirm if the SALOME GUI framework has already implemented this possibility.

**Comment by martin-bernhard** [comment]
AFAIK, SALOME does not support that functionality.
Keep in mind, that SALOME is a Single Document Application (SDA), where only one study at a time can be open, although you are able to work from on the same data in different modules, like creating geometry in GEOM/SHAPER, meshing it in SMESH and visualizing simulation results in PARAVIS.
SALOME also allows to create multiple windows for the different data types, but the data to all actions is common.
As long as your services are working on the same data (or on different parts of the common data set), you may be good.
Sorry for not being more helpful.

**Comment by louislau86** [comment]
Thank you all the same
